language: node_js
node_js:
  - 13

service: 
  - docker

# Script to be run such as tests
before_script:
  - echo "no tests"

script: 
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-user ./udagram-api-user

  - docker tag udagram-api-feed shine102/udagram-api-feed:v1
  - docker tag reverseproxy shine102/udagram-reverseproxy:v1
  - docker tag udagram-frontend shine102/udagram-frontend:v1
  - docker tag udagram-api-user shine102/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shine102/udagram-api-feed:v1
  - docker push shine102/udagram-reverseproxy:v1
  - docker push shine102/udagram-frontend:v1
  - docker push shine102/udagram-api-user:v1